name: Releases
on:
  push:
#    branches:
#      - main

jobs:
  audio-mixer-changelog-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: conventional Changelog Action audio-mixer
        id: changelog-audio-mixer
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          tag-prefix: audio-mixer-
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './audio-mixer/package.json'
          output-file: './audio-mixer/CHANGELOG.md'
          
      - name: create audio-mixer release
        uses: actions/create-release@v1
        if: ${{ steps.changelog-audio-mixer.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog-audio-mixer.outputs.tag }}
          release_name: ${{ steps.changelog-audio-mixer.outputs.tag }}
          body: ${{ steps.changelog-audio-mixer.outputs.changelog }}

  video-composer-changelog:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: conventional Changelog Action video-composer
        id: changelog-video-composer
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          tag-prefix: video-composer-
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './video-composer/package.json'
          output-file: './video-composer/CHANGELOG.md'
      - name: create video-composer release
        uses: actions/create-release@v1
        if: ${{ steps.changelog-video-composer.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog-video-composer.outputs.tag }}
          release_name: ${{ steps.changelog-video-composer.outputs.tag }}
          body: ${{ steps.changelog-video-composer.outputs.changelog }}
