name: Releases
on:
  push:
    branches:
      - main

jobs:
  audio-mixer-changelog:
    runs-on: ubuntu-latest
    outputs:
      audio-mixer-skipped: ${{ steps.changelog-audio-mixer.outputs.skipped }}
      audio-mixer-tag: ${{ steps.changelog-audio-mixer.outputs.tag }}
      audio-mixer-changelog: ${{ steps.changelog-audio-mixer.outputs.changelog }}
    steps:
      - uses: actions/checkout@v2
      - name: conventional Changelog Action audio-mixer
        id: changelog-audio-mixer
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          tag-prefix: audio-mixer-
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './audio-mixer/package.json'
          output-file: './audio-mixer/CHANGELOG.md'

  release-audio-mixer:
    runs-on: ubuntu-latest
    needs: audio-mixer-changelog
    steps:
      - name: create audio-mixer release
        uses: actions/create-release@v1
        if: ${{ needs.audio-mixer-changelog.outputs.audio-mixer-skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.audio-mixer-changelog.outputs.audio-mixer-tag }}
          release_name: ${{ needs.audio-mixer-changelog.outputs.audio-mixer-tag }}
          body: ${{ needs.audio-mixer-changelog.outputs.audio-mixer-changelog }}

  video-composer-changelog:  
    runs-on: ubuntu-latest
    outputs:
      video-composer-skipped: ${{ steps.changelog-video-composer.outputs.skipped }}
      video-composer-tag: ${{ steps.changelog-video-composer.outputs.tag }}
      video-composer-changelog: ${{ steps.changelog-video-composer.outputs.changelog }}
    steps:
      - uses: actions/checkout@v2
      - name: conventional Changelog Action video-composer
        id: changelog-video-composer
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          tag-prefix: video-composer-
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './video-composer/package.json'
          output-file: './video-composer/CHANGELOG.md'

  release-video-composer:
    runs-on: ubuntu-latest
    needs: video-composer-changelog
    steps:
      - name: create video-composer release
        uses: actions/create-release@v1
        if: ${{ needs.video-composer-changelog.outputs.video-composer-skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.video-composer-changelog.outputs.video-composer-tag }}
          release_name: ${{ needs.video-composer-changelog.outputs.video-composer-tag }}
          body: ${{ needs.video-composer-changelog.outputs.video-composer-changelog }}
