name: Release and Deploy Extension

on:
  workflow_dispatch:
    inputs:
      extension-name:
        type: choice
        required: true
        description: Extension to Release
        options: 
        - audio-mixer
        - video-composer
      release-type:
        type: choice
        required: true
        description: Release Version Type
        options: 
        - Major
        - Minor/Patch
      release-environment:
        type: choice
        required: true
        description: Release Environment
        options: 
        - Preview
        - Stable

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
      id: extract_branch

    - name: Send greeting
      run: |
        echo "${{ steps.extract_branch.outputs.branch }} | ${{ github.event.inputs.extension-name }} | ${{ github.event.inputs.release-type }} | ${{ github.event.inputs.release-environment }}"
