name: Release and Deploy Minor/Patch Version

on:
  workflow_dispatch:
    inputs:
      extension-name:
        type: choice
        required: true
        description: Extension to Release
        options: 
        - audio-mixer
        - video-composer
      release-environment:
        type: choice
        required: true
        description: Release Environment
        options: 
        - Preview
        - Stable

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Set input as env variables
      run: |
        echo "extension_name=${{ github.event.inputs.extension-name }}" >> $GITHUB_ENV
        echo "release_environment=${{ github.event.inputs.release-environment }}" >> $GITHUB_ENV

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
        
    - uses: actions/checkout@v1

    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: '${{ github.event.inputs.extension-name }}/package.json'
        prop_path: 'version'
        
    - name: Set version to env
      run: echo "release_version=${{ steps.version.outputs.prop }}" >> $GITHUB_ENV
                      
    - name: Compute Release Name
      uses: actions/github-script@v6
      id: release-name
      with:
        script: |
          const { extension_name, release_environment, release_version } = process.env;

          return release_environment == 'Preview' ? `${extension_name}-${release_version}-beta` : `${extension_name}-${release_version}`;
        result-encoding: string
        
    - name: Is Preview Release
      id: is-preview-release
      run: echo "::set-output name=isPreviewRelease::${{ github.event.inputs.release-environment == 'Preview' }}"

    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"
      
    - name: Perform Release
      id: release
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: '${{ steps.release-name.outputs.result }}',
            name: '${{ steps.release-name.outputs.result }}',
            prerelease: '${{ steps.is-preview-release.outputs.isPreviewRelease }}',
            generate_release_notes: true
          });

