name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn
      
      - name: Setup CI Git User
        run: |
          git config --global user.email "rjun.86@gmail.com"
          git config --global user.name "rjunsk"

      - name: Create Release Pull Request
        id: release_step
        uses: changesets/action@v1
        with:
          publish: yarn release
          setupGitUser: false
          commit: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output release
        run: |
          echo ${{ steps.release_step.outputs.published }}
          echo ${{ steps.release_step.outputs.publishedPackages }}
